services:
  app:
    image: mysociety/uk_local_authority_names_and_codes:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/workspaces/uk_local_authority_names_and_codes/