name: Test and build data

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push: 
    branches: ["main"]
  pull_request:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Run tests and try and build project
        uses: ./.github/actions/in-dev-container
        with:
          run: |
            script/test
            dataset build --all
            dataset version auto --auto-ban major
            dataset publish --all
            
      - name: Push new data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update local authority data based on source changes"