name: Run project tests

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-tests
  cancel-in-progress: true
  
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Run project tests
        uses: ./.github/actions/in-dev-container
        with:
          run: |
            script/bootstrap
            script/test